/*
Created by Lukas Deward 21.06.2021
Example function: SmallAlert('Error Message', 'Red', 'White', 3);
                            MESSAGE  BG COLOR  FONT COLOR  DURATION

UPDATE 22.06.2021 
Added BigAlert() and Notify()

UPDATE 27.06.2021
Added Target in SmallAlert(). With target you can include an URL OR an JS Function to be executed when the Notification is clicked
*/
var cssfile="https://lukvx.de/alert/alert.css";

let div=document.createElement("div");div.classList.add("small_alert"),div.setAttribute("id","small_alert"),document.body.appendChild(div);let div2=document.createElement("div");div2.classList.add("big_alert"),div2.setAttribute("id","big_alert"),document.body.appendChild(div2),bigalert=document.getElementById("big_alert");let button=document.createElement("button");function disableScrolling(){let e=window.scrollX,t=window.scrollY;window.onscroll=function(){window.scrollTo(e,t)}}function enableScrolling(){window.onscroll=function(){}}function BigAlertDissapear(){let e=document.getElementById("big_alert");e.innerHTML="<button id='button' onclick='BigAlertDissapear()' style='display: none;'></button>",e.style.display="none",enableScrolling()}function Notify(e){SmallAlert(e,"#5a5a5aa1","white",5)}function validURL(e){return!!new RegExp("^(https?:\\/\\/)?((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|((\\d{1,3}\\.){3}\\d{1,3}))(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*(\\?[;&a-z\\d%_.~+=-]*)?(\\#[-a-z\\d_]*)?$","i").test(e)}function SmallAlert(e,t,l,n,i){n*=1e3;let d=document.getElementById("small_alert");d.innerHTML=e,d.classList.remove("small_alert"),d.classList.add("small_alert_displayed"),d.style.backgroundColor=t,d.style.color=l,d.addEventListener("click",function(){if(null!=i)if(1==validURL(i))window.location.href=i;else{let e=i.split("("),arguments=e[1].split(")")[0].split(", ");"function"==typeof window[e[0]]?window[e[0]](arguments):console.warn(e[0]+" is not defined")}d.classList.remove("small_alert_displayed"),d.classList.add("small_alert")}),setTimeout(function(){d.classList.remove("small_alert_displayed"),d.classList.add("small_alert")},n)}function BigAlert(e,t,l,n){BigAlertDissapear();let i=document.getElementById("button");i.innerHTML="Okey",i.style.display="block",i.style.backgroundColor=n,i.style.color=l;let d=document.getElementById("big_alert");d.innerHTML="<h1>"+e+"</h1>"+t+d.innerHTML,d.style.backgroundColor=l,d.style.color=n,d.style.display="block",disableScrolling()}button.setAttribute("id","button"),button.setAttribute("onclick","BigAlertDissapear()"),button.style.display="none",bigalert.appendChild(button),bigalert.style.display="none";var cssId="alert";if(!document.getElementById(cssId)){var head=document.getElementsByTagName("head")[0],link=document.createElement("link");link.id=cssId,link.rel="stylesheet",link.type="text/css",link.href=cssfile,link.media="all",head.appendChild(link)}
